version: '3.7'
services:
  tickat-php:
    build:
      context: .
      dockerfile: ./docker/dev/php-fpm/Dockerfile
    container_name: tickat-php
    volumes:
      - ./:/var/www/html

  tickat-nginx:
    build: ./docker/dev/nginx
    container_name: tickat-nginx
    depends_on:
      - tickat-php
    ports:
      - 8080:80
      - 443:443
    volumes:
      - ./:/var/www/html
      - ./docker/dev/nginx/default.conf:/etc/nginx/conf.d/default.conf

  tickat-mysql:
    image: mysql:latest
    container_name: tickat-mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=tickat
      - MYSQL_ROOT_USERNAME=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
    volumes:
      - ./storage/.db:/var/lib/mysql
    security_opt:
      - seccomp:unconfined
